main:
  - name: mirrord
    weight: 10
    url: /
  - name: Pricing
    weight: 20
    url: /pricing/
  - name: Docs
    weight: 30
    url: /docs/overview/introduction/
  - name: Resources
    weight: 40
    identifier: resources
  - name: Blog
    parent: resources
    weight: 10
    url: "https://metalbear.co/blog"
  - name: Guides
    parent: resources
    weight: 20
    url: "https://metalbear.co/guides/"
  - name: Case Studies
    parent: resources
    weight: 30
    url: "https://metalbear.co/mirrord/case-studies/"
  - name: Contact us
    weight: 50
    url: /contact

main_mobile:
- name: Login/Sign Up
  url: "https://app.metalbear.co/"
  weight: 10
- name: Contact us
  url: "/contact/"
  weight: 20
- name: Schedule A Demo
  url: "/demo"
  weight: 30

docs:
  - name: Overview
    weight: 10
    identifier: overview
    url: /docs/overview/
  - name: Help
    weight: 60
    identifier: help
    url: /docs/help/
footer_menu:
- name: Get Started
  url: https://app.metalbear.co
  weight: 10
- name: Docs
  url: /docs/overview/introduction/
  weight: 20
- name: User Stories
  url: /stories/
  weight: 30
- name: Blog
  url: "https://metalbear.co/blog"
  weight: 40
- name: vs Telepresence
  url: /compare/telepresence/
  weight: 50
- name: vs Bridge to Kubernetes
  url: /compare/bridge-to-kubernetes/
  weight: 60
- identifier: contact
  name: Contact Us
  url: /contact
  weight: 70

footer_left:
  - name: Product Overview
    weight: 10
    url: /
  - name: User Stories
    weight: 20
    url: /stories/
  - name: Pricing
    weight: 30
    url: /pricing/
  - name: Contact us
    weight: 40
    url: /contact/
  - name: Careers - weâ€™re hiring!
    weight: 50
    url: "https://metalbear.co/careers"
footer_center:
  - name: Blog
    weight: 10
    url: "https://metalbear.co/blog"
  - name: Docs
    weight: 20
    url: /docs/overview/introduction/
  - name: Case Studies
    weight: 30
    url: "https://metalbear.co/mirrord/case-studies/"
  - name: vs Telepresence
    weight: 40
    url: /compare/telepresence/
  - name: vs Bridge to Kubernetes
    weight: 50
    url: /compare/bridge-to-kubernetes/
footer_right:
  - name: How to Debug a Java Microservice
    weight: 10
    url: "https://metalbear.co/guides/how-to-debug-a-java-microservice/"
  - name: How to Debug a Ruby Microservice
    weight: 20
    url: "https://metalbear.co/guides/how-to-debug-a-ruby-microservice/"
  - name: How to Debug a Go Microservice
    weight: 30
    url: "https://metalbear.co/guides/how-to-debug-a-go-microservice/"
  - name: How to Debug a Kotlin Microservice
    weight: 31
    url: "https://metalbear.co/guides/how-to-debug-a-kotlin-microservice/"
  - name: How to Debug a NodeJS Microservice
    weight: 32
    url: "https://metalbear.co/guides/how-to-debug-a-nodejs-microservice/"
  - name: How to Debug a PHP Microservice
    weight: 33
    url: "https://metalbear.co/guides/how-to-debug-a-php-microservice/"

social:
- name: Slack
  pre: slack
  url: https://metalbear.co/slack
  weight: 10
- name: Github
  pre: github
  url: https://github.com/metalbear-co/mirrord
  weight: 20
- name: Twitter
  pre: twitter
  url: https://twitter.com/metalbearco
  weight: 30
- name: Linkedin
  pre: linkedin
  url: https://www.linkedin.com/company/metalbearco/
  weight: 40

footer_social:
  - name: Slack
    pre: '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"><g><rect width="35" height="35" rx="8" fill="#611F69"/><path d="M10.5 19.25a2.25 2.25 0 1 1 0-4.5h2.25v4.5H10.5Zm1.125-2.25a2.25 2.25 0 1 1 4.5 0v6.75a2.25 2.25 0 1 1-4.5 0v-6.75Zm2.25 1.125a2.25 2.25 0 1 1 4.5 0v2.25a2.25 2.25 0 1 1-4.5 0v-2.25Zm2.25-1.125a2.25 2.25 0 1 1 4.5 0v6.75a2.25 2.25 0 1 1-4.5 0v-6.75Zm2.25 1.125a2.25 2.25 0 1 1 4.5 0v2.25a2.25 2.25 0 1 1-4.5 0v-2.25Z" fill="white"/></g></svg>'
    url: https://metalbear.co/slack
    weight: 10
  - name: Twitter
    pre: '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none"
      xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_596_1331)">
      <path d="M31.3826 6.01445C31.3826 6.01445 28.8658 7.49536 27.4665
      7.91528C26.7154 7.05495 25.7172 6.44517 24.6069 6.16841C23.4965 5.89165
      22.3277 5.96127 21.2583 6.36784C20.189 6.77442 19.2708 7.49834 18.628
      8.44169C17.9851 9.38505 17.6486 10.5023 17.6639 11.6424V12.8848C15.4722
      12.9414 13.3005 12.4572 11.3422 11.4752C9.38381 10.4933 7.69963 9.04415
      6.43961 7.25682C6.43961 7.25682 1.45101 18.4382 12.6754 23.4077C10.1069
      25.1445 7.04717 26.0154 3.94531 25.8924C15.1697 32.1043 28.8883 25.8924
      28.8883 11.6051C28.8883 11.2598 28.8534 10.9144 28.7885 10.574C30.0606
      9.32413 31.3826 6.01445 31.3826 6.01445Z" fill="black" stroke="black"
      stroke-width="0.857415" stroke-linecap="round" stroke-linejoin="round"/>
      </g> <defs> <clipPath id="clip0_596_1331"> <rect width="34.2966"
      height="34.2966" fill="white" transform="translate(0.515625)"/>
      </clipPath> </defs> </svg> '
    url: https://twitter.com/metalbearco
    weight: 30
  - name: GitHub
    pre: '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none"
      xmlns="http://www.w3.org/2000/svg"> <path d="M25.2871 5.58496C25.6461
      5.54637 25.9231 5.59874 26.1338 5.77539L26.2197 5.8584C26.3906 6.04822
      26.5147 6.32405 26.6055 6.66211C26.6505 6.82999 26.6855 7.00401 26.7139
      7.17773L26.7861 7.69434V7.69531C26.8763 8.40981 26.8948 9.32539 26.665
      10.2227L26.6133 10.4258L26.7412 10.5918C27.6374 11.7491 28.1689 13.1172
      28.1689 14.5996C28.1689 16.7015 27.1024 18.5676 25.4453 19.9355L25.1084
      20.2002C24.2155 20.8616 23.2251 21.3802 22.1729 21.7373L21.7305
      21.8877L21.917 22.3154C22.1461 22.84 22.2744 23.4207 22.2744
      24.0312V27.5684C22.2743 27.7174 22.2299 27.8622 22.1484 27.9844L22.0547
      28.0986C21.914 28.2393 21.7224 28.3184 21.5234 28.3184H14.4502C14.3011
      28.3184 14.1565 28.2738 14.0342 28.1924L13.9199 28.0986C13.7793 27.9581
      13.7003 27.7672 13.7002 27.5684V25.915L13.2188 25.9736C12.2866 26.0878
      11.5067 26.0114 10.8428 25.7852L10.5654 25.6797C9.90441 25.3993 9.4139
      24.9825 9.02441 24.5498L8.86328 24.3643V24.3633L8.73047 24.1836C8.68291
      24.1135 8.63128 24.0335 8.5752 23.9434C8.46881 23.7724 8.34494 23.5655
      8.21582 23.3721C8.08566 23.1771 7.93655 22.9749 7.76758 22.8027C7.62081
      22.6533 7.44379 22.5097 7.23242 22.4199L7.13965 22.3857V22.3848C7.09284
      22.3692 7.04754 22.3495 7.00488 22.3252L6.88477 22.2402C6.8477 22.2081
      6.81415 22.1723 6.78418 22.1338L6.70508 22.0088C6.63835 21.8753 6.6136
      21.726 6.63184 21.5801L6.66406 21.4365C6.71125 21.2948 6.79984 21.1714
      6.91602 21.0811L7.04102 21.002C7.17454 20.9352 7.32375 20.9104 7.46973
      20.9287L7.61328 20.9609C8.19147 21.1537 8.60551 21.5463 8.9248
      21.9336L9.05664 22.0986V22.0996C9.18937 22.2711 9.31739 22.4571 9.45605
      22.6582C9.59198 22.8554 9.73806 23.0656 9.89648 23.2666C10.1737 23.6183
      10.5091 23.9675 10.9531 24.2041L11.1504 24.2979C11.6041 24.4906 12.2253
      24.5963 13.1318 24.4727L13.1465 24.4707L13.1602 24.4678L13.3564
      24.4277L13.6982 24.3584L13.7002 24.0088C13.702 23.4987 13.7951 22.9938
      13.9746 22.5176L14.0566 22.3154L14.2432 21.8877L13.8018 21.7373C12.7493
      21.3802 11.7583 20.8617 10.8652 20.2002H10.8643C9.01684 18.8132 7.80571
      16.8414 7.80566 14.5996C7.80566 13.1195 8.33569 11.7528 9.22949
      10.5967L9.35742 10.4307L9.30566 10.2275C9.076 9.33067 9.09368 8.41342
      9.18359 7.69824L9.18945 7.65332V7.65137C9.23315 7.30301 9.27651 6.95909
      9.36328 6.63867C9.44955 6.32022 9.57149 6.05616 9.75 5.8584L9.74902
      5.85742C9.9684 5.61489 10.2724 5.54159 10.6826 5.58594C11.1064 5.6318
      11.5514 5.79399 11.9814 5.94043L12.0801 5.97363C12.8943 6.25858 13.6698
      6.64426 14.3877 7.12305L14.5469 7.22949L14.7324 7.18164C15.6628 6.9439
      16.6162 6.80977 17.5752 6.78125L17.9863 6.77539H17.9873C19.1223 6.77542
      20.216 6.91743 21.2393 7.18066L21.4248 7.22852L21.584 7.12207C22.2368
      6.68692 22.9371 6.32829 23.6709 6.05273L23.9873 5.93945H23.9883C24.4189
      5.79303 24.8635 5.63052 25.2871 5.58496Z" fill="black" stroke="black"
      stroke-width="0.857415"/> </svg> '
    url: https://github.com/metalbear-co/mirrord
    post: v0.1.0
    weight: 20
  - name: Linkedin
    pre: '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none"
      xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_596_1333)">
      <path d="M28.0458 5.97949H8.39298C7.45313 5.97949 6.69043 6.72426 6.69043
      7.64136V27.379C6.69043 28.2974 7.45313 29.0431 8.39298
      29.0431H28.0458C28.9863 29.0431 29.7541 28.2974 29.7541
      27.379V7.64136C29.7541 6.72426 28.9863 5.97949 28.0458 5.97949ZM13.5307
      25.6329H10.1083V14.6268H13.5307V25.6329ZM11.8195 13.1219C11.559 13.1219
      11.3011 13.0705 11.0604 12.9708C10.8198 12.8711 10.6011 12.7249 10.417
      12.5406C10.2329 12.3564 10.0868 12.1377 9.98726 11.8969C9.88769 11.6562
      9.83653 11.3982 9.8367 11.1377C9.8367 10.6119 10.0456 10.1076 10.4174
      9.73578C10.7892 9.36396 11.2935 9.15507 11.8194 9.15507C12.3452 9.15507
      12.8495 9.36396 13.2213 9.73578C13.5932 10.1076 13.802 10.6119 13.802
      11.1377C13.802 11.6637 13.5932 12.1681 13.2215 12.5402C12.8497 12.9122
      12.3455 13.1214 11.8195 13.1219ZM26.3426 25.6329H22.9256V20.2809C22.9256
      19.0041 22.9007 17.3624 21.1475 17.3624C19.3671 17.3624 19.0958 18.7529
      19.0958 20.1883V25.6333H15.6763V14.6268H18.9581V16.1297H19.0048C19.4616
      15.2649 20.5776 14.3522 22.2421 14.3522C25.7035 14.3522 26.3429 16.6311
      26.3429 19.5957V25.6329H26.3426Z" fill="black"/> </g> <defs> <clipPath
      id="clip0_596_1333"> <rect width="34.1684" height="34.1684" fill="white"
      transform="translate(0.710938)"/> </clipPath> </defs> </svg> '
    url: https://www.linkedin.com/company/metalbearco
    weight: 40

