# Meta Data for SEO

## Homepage
title = "MetalBear üêª"
titleSeparator = "|"
titleAddition = "Creators of mirrord"
description = "Collection of advanced guides for cloud native developers who want to spend more time coding not waiting for CI"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["metalbear.png"]
ogLocale = "en_US"
domainTLD = "metalbear.co"
titleHome = "MetalBear üêª"

## Twitter Cards
twitterSite = "@metalbearco"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "MetalBear"
schemaAuthor = "MetalBear"
schemaAuthorTwitter = "https://twitter.com/metalbearco"
schemaAuthorLinkedIn = "https://www.linkedin.com/company/metalbearco"
schemaAuthorGitHub = "https://github.com/metalbear-co"
schemaLocale = "en-US"
schemaLogo = "metalbear.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "metalbear.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/metalbearco"
schemaLinkedIn = "https://www.linkedin.com/company/metalbearco"
schemaGitHub = "https://github.com/metalbear-co"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "¬© MetalBear"

# Feed
copyRight = "Copyright (c) 2022 MetalBear"

# Alert
alert = false
alertDismissable = true
alertText = "mirrord for Teams is live on Product Hunt! <a class=\"alert-link stretched-link\" href=\"https://www.producthunt.com/posts/mirrord-for-teams\" rel=\"noopener\" target=\"_blank\">Check out the launch and share your feedback!</a>"

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/metalbear-co/metalbear.co"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
lazySizes = true
clipBoard = true
instantPage = true
flexSearch = true
darkMode = false
bootStrapJs = true
breadCrumb = false
highLight = true
kaTex = false
multilingualMode = false
docsVersioning = false
fullWidth = false

[menu]
[menu.section]
auto = true
collapsibleSidebar = true
