[[main]]
name = "mirrord"
weight = 10
url = "/mirrord/"

[[main]]
name = "Pricing"
weight = 20
url = "/mirrord/pricing/"

[[main]]
name = "Docs"
weight = 30
url = "/mirrord/docs/overview/introduction/"

[[main]]
name = "Resources"
weight = 40
identifier = "resources"

[[main]]
name = "Blog"
parent = "resources"
weight = 10
url = "/blog/"

[[main]]
name = "Guides"
parent = "resources"
weight = 20
url = "/guides/"

[[main]]
name = "Case Studies"
parent = "resources"
weight = 30
url = "/mirrord/case-studies/"

[[main]]
name = "Contact us"
weight = 50
url = "/contact"

[[footer_left]]
name = "Product Overview"
weight = 10
url = "/mirrord/"

[[footer_left]]
name = "User Stories"
weight = 20
url = "/mirrord/stories/"

[[footer_left]]
name = "Pricing"
weight = 30
url = "/mirrord/pricing/"

[[footer_left]]
name = "Contact us"
weight = 40
url = "/mirrord/contact/"

[[footer_center]]
name = "Blog"
weight = 10
url = "/blog/"

[[footer_center]]
name = "Docs"
weight = 20
url = "/mirrord/docs/overview/introduction/"

[[footer_center]]
name = "Case Studies"
weight = 30
url = "/mirrord/case-studies/"

[[footer_center]]
name = "vs Telepresence"
weight = 40
url = "/mirrord/compare/telepresence/"

[[footer_center]]
name = "vs Bridge to Kubernetes"
weight = 50
url = "/mirrord/compare/bridge-to-kubernetes/"

[[footer_right]]
name = "How to Debug a Java Microservice"
weight = 10
url = "/guides/how-to-debug-a-java-microservice/"

[[footer_right]]
name = "How to Debug a Ruby Microservice"
weight = 20
url = "/guides/how-to-debug-a-ruby-microservice/"

[[footer_right]]
name = "How to Debug a Go Microservice"
weight = 30
url = "/guides/how-to-debug-a-go-microservice/"

[[footer_right]]
name = "How to Debug a Kotlin Microservice"
weight = 31
url = "/guides/how-to-debug-a-kotlin-microservice/"

[[footer_right]]
name = "How to Debug a NodeJS Microservice"
weight = 32
url = "/guides/how-to-debug-a-nodejs-microservice/"

[[footer_right]]
name = "How to Debug a PHP Microservice"
weight = 33
url = "/guides/how-to-debug-a-php-microservice/"

[[social]]
name = "Discord"
pre = '<svg width="28" height="21" viewBox="0 0 32 25" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M26.6957 2.33823C26.684 2.32193 26.6735 2.30473 26.6642 2.28673L27.0312 2.09733L27.036 2.09484L27.1085 2.05743L27.0293 2.11133L27.0227 2.11577L26.6957 2.33823ZM26.7546 2.42644C30.2341 7.57889 31.959 13.3676 31.3545 20.0248C29.0971 21.6731 26.5882 22.9453 23.9251 23.7926C23.4821 23.1598 23.0747 22.5029 22.7049 21.8248C23.4456 21.5235 24.164 21.1698 24.8549 20.7665L24.8549 20.7665L24.8593 20.7639C24.9442 20.7132 25.0153 20.6423 25.0664 20.5575C25.1174 20.4728 25.1468 20.3768 25.1519 20.278C25.157 20.1791 25.1377 20.0806 25.0957 19.991C25.0537 19.9015 24.9903 19.8236 24.9111 19.7643L24.9103 19.7637C24.7482 19.643 24.5891 19.5183 24.4332 19.3897L24.4313 19.3881C24.3435 19.3164 24.2372 19.2712 24.1247 19.2575C24.014 19.2441 23.9018 19.2619 23.8008 19.3088C18.7639 21.6351 13.2513 21.6361 8.1497 19.3078L8.14649 19.3064C8.04472 19.2608 7.93223 19.2446 7.8217 19.2594C7.71137 19.2743 7.6074 19.3196 7.52142 19.3903C7.36526 19.5186 7.20616 19.6432 7.04425 19.7642L7.04424 19.7641L7.041 19.7666C6.96223 19.8264 6.8994 19.9048 6.85807 19.9946C6.81674 20.0845 6.79818 20.1832 6.80402 20.2819C6.80987 20.3807 6.83994 20.4765 6.89158 20.5609C6.94322 20.6452 7.01485 20.7156 7.10013 20.7658L7.10344 20.7677C7.79634 21.1679 8.51506 21.5213 9.25477 21.8256C8.88929 22.5064 8.48132 23.1637 8.03329 23.7934C5.3743 22.9436 2.86914 21.6714 0.614059 20.0254C0.107993 14.2557 1.22354 8.4219 5.20918 2.42723C7.12628 1.55683 9.14252 0.924457 11.2129 0.544051C11.4545 0.989374 11.6754 1.44575 11.8747 1.9117L12.0268 2.26749L12.4094 2.20941C14.7824 1.8492 17.1961 1.8492 19.569 2.20941L19.9522 2.26758L20.104 1.91102C20.3019 1.44654 20.5194 0.990696 20.7558 0.544722C22.8242 0.925774 24.8387 1.55763 26.7546 2.42644ZM20.8923 0.292173C20.8921 0.292496 20.892 0.292818 20.8918 0.293141C20.8919 0.292903 20.892 0.292668 20.8922 0.292431L20.8923 0.292173ZM24.0922 24.0278L24.0908 24.0258C24.0912 24.0264 24.0917 24.0271 24.0922 24.0278ZM31.4993 19.9183L31.4965 19.9204C31.4974 19.9197 31.4984 19.919 31.4993 19.9183ZM7.31105 13.3953C7.31105 15.3927 8.78171 17.1165 10.6845 17.1165C12.614 17.1165 14.0563 15.3917 14.058 13.3987C14.0846 11.4088 12.6232 9.67393 10.6845 9.67393C8.75385 9.67393 7.31105 11.4009 7.31105 13.3953ZM17.9352 13.3953C17.9352 15.3927 19.4059 17.1165 21.3087 17.1165C23.2521 17.1165 24.6804 15.3903 24.6822 13.3988C24.7089 11.4088 23.2475 9.67393 21.3087 9.67393C19.378 9.67393 17.9352 11.4009 17.9352 13.3953Z" fill="currentColor" stroke="currentColor"/></svg>'
url = "https://discord.gg/metalbear"
weight = 10

[[social]]
name = "Twitter"
pre = '<svg width="28" height="22" viewBox="0 0 34 28" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M33 1.01457C33 1.01457 30.0647 2.74175 28.4327 3.23151C27.5567 2.2281 26.3925 1.51692 25.0975 1.19414C23.8025 0.871354 22.4393 0.952548 21.1921 1.42674C19.945 1.90093 18.8741 2.74523 18.1243 3.84546C17.3746 4.94569 16.9821 6.24877 17 7.57844V9.02742C14.4438 9.09345 11.9109 8.5287 9.62692 7.38347C7.3429 6.23825 5.37864 4.5481 3.90909 2.46355C3.90909 2.46355 -1.90909 15.5044 11.1818 21.3003C8.18622 23.3259 4.61768 24.3416 1 24.1982C14.0909 31.4431 30.0909 24.1982 30.0909 7.53497C30.0909 7.13216 30.0502 6.72934 29.9745 6.33232C31.4582 4.87465 33 1.01457 33 1.01457Z" fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg>'
url = "https://twitter.com/metalbearco"
weight = 20

[[social]]
name = "GitHub"
pre = '<svg width="22" height="23" viewBox="0 0 27 28" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0.983615 18.4945C1.19117 18.3906 1.43148 18.3735 1.6517 18.4467C2.42236 18.7036 2.94305 19.2647 3.33441 19.7733L3.33533 19.7745C3.48399 19.9665 3.62716 20.1742 3.78151 20.3981L3.80071 20.426C3.95931 20.6561 4.12938 20.9017 4.31424 21.1362C4.68365 21.6049 5.14187 22.0693 5.77637 22.3389L5.7764 22.339C6.30563 22.5638 7.03061 22.6863 8.08831 22.5419L8.10447 22.5397L8.12044 22.5365L8.35007 22.4897L8.74889 22.4085L8.75031 22.0015C8.7527 21.3215 8.89431 20.6492 9.16642 20.026L9.38417 19.5273L8.86883 19.3524C7.64186 18.9361 6.48706 18.3316 5.44581 17.5606C3.28984 15.9428 1.87532 13.6428 1.87532 11.0273C1.87532 9.30092 2.49382 7.70678 3.53637 6.35836L3.68578 6.16511L3.62518 5.92848C3.35717 4.88196 3.37774 3.81153 3.48273 2.97723L3.48942 2.92638L3.48943 2.92638L3.4898 2.92338C3.54076 2.51709 3.5915 2.1167 3.6927 1.743C3.79332 1.37144 3.93484 1.06327 4.1431 0.832553C4.39898 0.549474 4.75251 0.462669 5.23103 0.51441C5.68019 0.562975 6.14944 0.723863 6.60773 0.880993C6.65387 0.896811 6.69989 0.91259 6.74577 0.928213L6.95975 1.00108C7.87359 1.32984 8.74434 1.76856 9.55275 2.30774L9.73812 2.43138L9.954 2.37621C11.1942 2.05924 12.4694 1.90001 13.7494 1.90228H13.7503C15.0742 1.90228 16.3495 2.0676 17.5431 2.37464L17.7593 2.43024L17.945 2.30644C18.8153 1.7263 19.7579 1.26258 20.7486 0.927112L20.7492 0.926908C20.7949 0.911346 20.8408 0.89563 20.8868 0.879879C21.3458 0.722755 21.8152 0.562056 22.2643 0.513753C22.7424 0.462338 23.0958 0.549215 23.3518 0.832337C23.5513 1.05384 23.6965 1.37574 23.8025 1.77045C23.9077 2.16237 23.963 2.58104 24.0122 2.97404L24.0122 2.97462C24.1174 3.8081 24.1394 4.87621 23.8713 5.92298L23.8107 6.15984L23.9604 6.35315C25.0055 7.70291 25.6253 9.29832 25.6253 11.0273C25.6253 13.6414 24.2108 15.9427 22.0549 17.5605C21.0136 18.3316 19.8588 18.9361 18.6318 19.3524L18.1164 19.5273L18.3342 20.026C18.6015 20.6379 18.7503 21.3151 18.7503 22.0273V26.1523C18.7503 26.3843 18.6581 26.6069 18.494 26.771C18.3299 26.9351 18.1074 27.0273 17.8753 27.0273H9.62532C9.39325 27.0273 9.17069 26.9351 9.0066 26.771C8.8425 26.6069 8.75032 26.3843 8.75032 26.1523V24.7897V24.2247L8.18951 24.2934C6.94709 24.4456 5.93648 24.3071 5.09477 23.9499L5.09468 23.9498C4.21372 23.5762 3.59232 22.995 3.10982 22.4155L3.10938 22.415C3.01261 22.299 2.90454 22.135 2.77376 21.9248C2.74299 21.8753 2.71095 21.8233 2.67787 21.7696C2.57749 21.6067 2.46751 21.4281 2.3542 21.2584C2.20236 21.031 2.02882 20.795 1.83169 20.5942C1.63605 20.3949 1.39371 20.2061 1.09893 20.1078L1.09878 20.1078C0.989716 20.0714 0.888877 20.014 0.802017 19.9387C0.715156 19.8634 0.643974 19.7718 0.592534 19.669C0.488649 19.4614 0.47149 19.221 0.544832 19.0007C0.618174 18.7805 0.77601 18.5984 0.983615 18.4945Z" fill="currentColor" stroke="currentColor"/></svg>'
url = "https://github.com/metalbear-co/mirrord"
post = "v0.1.0"
weight = 30

[[social]]
name = "Linkedin"
pre = '<svg width="22" height="22" viewBox="0 0 27 27" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M25.0001 0H1.99313C0.892875 0 0 0.871875 0 1.9455V25.0519C0 26.127 0.892875 27 1.99313 27H25.0001C26.1011 27 27 26.127 27 25.0519V1.9455C27 0.871875 26.1011 0 25.0001 0ZM8.00775 23.0077H4.00125V10.1231H8.00775V23.0077ZM6.0045 8.36138C5.69954 8.36138 5.39757 8.30128 5.11585 8.18454C4.83412 8.06779 4.57817 7.89667 4.3626 7.68097C4.14703 7.46526 3.97608 7.20919 3.85951 6.92739C3.74295 6.64559 3.68305 6.34358 3.68325 6.03863C3.68325 5.42304 3.92779 4.83267 4.36307 4.39739C4.79836 3.9621 5.38873 3.71756 6.00431 3.71756C6.6199 3.71756 7.21027 3.9621 7.64555 4.39739C8.08084 4.83267 8.32537 5.42304 8.32537 6.03863C8.32538 6.65433 8.08092 7.24485 7.64572 7.68039C7.21053 8.11594 6.62021 8.36088 6.0045 8.36138ZM23.0062 23.0077H19.0061V16.7423C19.0061 15.2475 18.9769 13.3256 16.9245 13.3256C14.8403 13.3256 14.5226 14.9535 14.5226 16.6339V23.0081H10.5195V10.1231H14.3614V11.8826H14.4161C14.9509 10.8701 16.2574 9.80175 18.2059 9.80175C22.2581 9.80175 23.0066 12.4695 23.0066 15.9401V23.0077H23.0062Z" fill="currentColor"/></svg>'
url = "https://www.linkedin.com/company/metalbearco"
weight = 40

[[footer_social]]
name = "Discord"
pre = '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_596_1332)"> <path d="M21.2256 7.32812C22.9991 7.65484 24.7264 8.19549 26.3691 8.94043C29.3524 13.358 30.8306 18.3207 30.3125 24.0283C28.3777 25.4409 26.2276 26.5305 23.9453 27.2568C23.5651 26.7138 23.2157 26.1503 22.8984 25.5684C23.3438 25.3871 23.781 25.1866 24.2061 24.9619L24.7402 24.665L24.7441 24.6631C24.7987 24.6305 24.8468 24.5878 24.8857 24.5381L24.9219 24.4854C24.9655 24.4128 24.9907 24.3307 24.9951 24.2461C24.9984 24.1825 24.9904 24.1188 24.9707 24.0586L24.9473 24L24.917 23.9443C24.8945 23.9085 24.8674 23.8759 24.8369 23.8467L24.7891 23.8057L24.7881 23.8047L24.3789 23.4844L24.377 23.4834L24.3184 23.4414C24.277 23.4164 24.2323 23.3973 24.1855 23.3848L24.1143 23.3711L24.042 23.3672C23.9939 23.3682 23.9463 23.3763 23.9004 23.3906L23.832 23.417C19.6495 25.3471 15.0847 25.4081 10.8281 23.5957L10.417 23.4141L10.415 23.4131L10.3477 23.3887C10.3019 23.3754 10.2546 23.3684 10.207 23.3682L10.1357 23.373C10.065 23.3826 9.99702 23.4063 9.93652 23.4434L9.87793 23.4854L9.46973 23.8057L9.4668 23.8076C9.41613 23.8461 9.37311 23.8935 9.33984 23.9473L9.30957 24.0029C9.28293 24.0609 9.26765 24.1232 9.26367 24.1865V24.249C9.26868 24.3337 9.29463 24.416 9.33887 24.4883C9.37207 24.5425 9.41463 24.5904 9.46484 24.6289L9.52051 24.666C10.1136 25.0086 10.7302 25.3078 11.3633 25.5684C11.0495 26.1531 10.6992 26.717 10.3145 27.2578C8.03566 26.5291 5.88877 25.4392 3.95605 24.0283C3.52241 19.0819 4.47889 14.0806 7.89551 8.94141C9.53944 8.19495 11.2686 7.65435 13.0439 7.32812C13.2507 7.70927 13.4408 8.09929 13.6113 8.49805L13.7412 8.80371L14.0693 8.75391C16.1038 8.44508 18.1735 8.44512 20.208 8.75391L20.5371 8.80371L20.667 8.49805C20.8364 8.10031 21.0232 7.71003 21.2256 7.32812ZM12.5908 15.1543C10.9354 15.1543 9.69824 16.6347 9.69824 18.3447C9.69827 20.0573 10.9593 21.5352 12.5908 21.5352C14.1427 21.5351 15.3268 20.2339 15.4688 18.6621L15.4834 18.3447C15.5048 16.6398 14.2521 15.1543 12.5908 15.1543ZM21.7002 15.1543C20.0448 15.1543 18.8076 16.6347 18.8076 18.3447C18.8076 20.0573 20.0687 21.5352 21.7002 21.5352C23.2632 21.5351 24.4374 20.2329 24.5781 18.6621L24.5928 18.3447C24.6142 16.6398 23.3615 15.1544 21.7002 15.1543Z" fill="black" stroke="black" stroke-width="0.857415"/> </g> <defs> <clipPath id="clip0_596_1332"> <rect width="34.2966" height="34.2966" fill="white"/> </clipPath> </defs> </svg>'
url = "https://discord.gg/metalbear"
weight = 10

[[footer_social]]
name = "Twitter"
pre = '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_596_1331)"> <path d="M31.3826 6.01445C31.3826 6.01445 28.8658 7.49536 27.4665 7.91528C26.7154 7.05495 25.7172 6.44517 24.6069 6.16841C23.4965 5.89165 22.3277 5.96127 21.2583 6.36784C20.189 6.77442 19.2708 7.49834 18.628 8.44169C17.9851 9.38505 17.6486 10.5023 17.6639 11.6424V12.8848C15.4722 12.9414 13.3005 12.4572 11.3422 11.4752C9.38381 10.4933 7.69963 9.04415 6.43961 7.25682C6.43961 7.25682 1.45101 18.4382 12.6754 23.4077C10.1069 25.1445 7.04717 26.0154 3.94531 25.8924C15.1697 32.1043 28.8883 25.8924 28.8883 11.6051C28.8883 11.2598 28.8534 10.9144 28.7885 10.574C30.0606 9.32413 31.3826 6.01445 31.3826 6.01445Z" fill="black" stroke="black" stroke-width="0.857415" stroke-linecap="round" stroke-linejoin="round"/> </g> <defs> <clipPath id="clip0_596_1331"> <rect width="34.2966" height="34.2966" fill="white" transform="translate(0.515625)"/> </clipPath> </defs> </svg> '
url = "https://twitter.com/metalbearco"
weight = 30

[[footer_social]]
name = "GitHub"
pre = '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M25.2871 5.58496C25.6461 5.54637 25.9231 5.59874 26.1338 5.77539L26.2197 5.8584C26.3906 6.04822 26.5147 6.32405 26.6055 6.66211C26.6505 6.82999 26.6855 7.00401 26.7139 7.17773L26.7861 7.69434V7.69531C26.8763 8.40981 26.8948 9.32539 26.665 10.2227L26.6133 10.4258L26.7412 10.5918C27.6374 11.7491 28.1689 13.1172 28.1689 14.5996C28.1689 16.7015 27.1024 18.5676 25.4453 19.9355L25.1084 20.2002C24.2155 20.8616 23.2251 21.3802 22.1729 21.7373L21.7305 21.8877L21.917 22.3154C22.1461 22.84 22.2744 23.4207 22.2744 24.0312V27.5684C22.2743 27.7174 22.2299 27.8622 22.1484 27.9844L22.0547 28.0986C21.914 28.2393 21.7224 28.3184 21.5234 28.3184H14.4502C14.3011 28.3184 14.1565 28.2738 14.0342 28.1924L13.9199 28.0986C13.7793 27.9581 13.7003 27.7672 13.7002 27.5684V25.915L13.2188 25.9736C12.2866 26.0878 11.5067 26.0114 10.8428 25.7852L10.5654 25.6797C9.90441 25.3993 9.4139 24.9825 9.02441 24.5498L8.86328 24.3643V24.3633L8.73047 24.1836C8.68291 24.1135 8.63128 24.0335 8.5752 23.9434C8.46881 23.7724 8.34494 23.5655 8.21582 23.3721C8.08566 23.1771 7.93655 22.9749 7.76758 22.8027C7.62081 22.6533 7.44379 22.5097 7.23242 22.4199L7.13965 22.3857V22.3848C7.09284 22.3692 7.04754 22.3495 7.00488 22.3252L6.88477 22.2402C6.8477 22.2081 6.81415 22.1723 6.78418 22.1338L6.70508 22.0088C6.63835 21.8753 6.6136 21.726 6.63184 21.5801L6.66406 21.4365C6.71125 21.2948 6.79984 21.1714 6.91602 21.0811L7.04102 21.002C7.17454 20.9352 7.32375 20.9104 7.46973 20.9287L7.61328 20.9609C8.19147 21.1537 8.60551 21.5463 8.9248 21.9336L9.05664 22.0986V22.0996C9.18937 22.2711 9.31739 22.4571 9.45605 22.6582C9.59198 22.8554 9.73806 23.0656 9.89648 23.2666C10.1737 23.6183 10.5091 23.9675 10.9531 24.2041L11.1504 24.2979C11.6041 24.4906 12.2253 24.5963 13.1318 24.4727L13.1465 24.4707L13.1602 24.4678L13.3564 24.4277L13.6982 24.3584L13.7002 24.0088C13.702 23.4987 13.7951 22.9938 13.9746 22.5176L14.0566 22.3154L14.2432 21.8877L13.8018 21.7373C12.7493 21.3802 11.7583 20.8617 10.8652 20.2002H10.8643C9.01684 18.8132 7.80571 16.8414 7.80566 14.5996C7.80566 13.1195 8.33569 11.7528 9.22949 10.5967L9.35742 10.4307L9.30566 10.2275C9.076 9.33067 9.09368 8.41342 9.18359 7.69824L9.18945 7.65332V7.65137C9.23315 7.30301 9.27651 6.95909 9.36328 6.63867C9.44955 6.32022 9.57149 6.05616 9.75 5.8584L9.74902 5.85742C9.9684 5.61489 10.2724 5.54159 10.6826 5.58594C11.1064 5.6318 11.5514 5.79399 11.9814 5.94043L12.0801 5.97363C12.8943 6.25858 13.6698 6.64426 14.3877 7.12305L14.5469 7.22949L14.7324 7.18164C15.6628 6.9439 16.6162 6.80977 17.5752 6.78125L17.9863 6.77539H17.9873C19.1223 6.77542 20.216 6.91743 21.2393 7.18066L21.4248 7.22852L21.584 7.12207C22.2368 6.68692 22.9371 6.32829 23.6709 6.05273L23.9873 5.93945H23.9883C24.4189 5.79303 24.8635 5.63052 25.2871 5.58496Z" fill="black" stroke="black" stroke-width="0.857415"/> </svg> '
url = "https://github.com/metalbear-co/mirrord"
post = "v0.1.0"
weight = 20

[[footer_social]]
name = "Linkedin"
pre = '<svg class="w-100 w-full h-auto" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg"> <g clip-path="url(#clip0_596_1333)"> <path d="M28.0458 5.97949H8.39298C7.45313 5.97949 6.69043 6.72426 6.69043 7.64136V27.379C6.69043 28.2974 7.45313 29.0431 8.39298 29.0431H28.0458C28.9863 29.0431 29.7541 28.2974 29.7541 27.379V7.64136C29.7541 6.72426 28.9863 5.97949 28.0458 5.97949ZM13.5307 25.6329H10.1083V14.6268H13.5307V25.6329ZM11.8195 13.1219C11.559 13.1219 11.3011 13.0705 11.0604 12.9708C10.8198 12.8711 10.6011 12.7249 10.417 12.5406C10.2329 12.3564 10.0868 12.1377 9.98726 11.8969C9.88769 11.6562 9.83653 11.3982 9.8367 11.1377C9.8367 10.6119 10.0456 10.1076 10.4174 9.73578C10.7892 9.36396 11.2935 9.15507 11.8194 9.15507C12.3452 9.15507 12.8495 9.36396 13.2213 9.73578C13.5932 10.1076 13.802 10.6119 13.802 11.1377C13.802 11.6637 13.5932 12.1681 13.2215 12.5402C12.8497 12.9122 12.3455 13.1214 11.8195 13.1219ZM26.3426 25.6329H22.9256V20.2809C22.9256 19.0041 22.9007 17.3624 21.1475 17.3624C19.3671 17.3624 19.0958 18.7529 19.0958 20.1883V25.6333H15.6763V14.6268H18.9581V16.1297H19.0048C19.4616 15.2649 20.5776 14.3522 22.2421 14.3522C25.7035 14.3522 26.3429 16.6311 26.3429 19.5957V25.6329H26.3426Z" fill="black"/> </g> <defs> <clipPath id="clip0_596_1333"> <rect width="34.1684" height="34.1684" fill="white" transform="translate(0.710938)"/> </clipPath> </defs> </svg> '
url = "https://www.linkedin.com/company/metalbearco"
weight = 40
